-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


    CREATE TABLE
    IF NOT EXISTS PUBLIC.customer
    (
    customer_id integer NOT NULL,
    customer_name character VARYING
    (50) COLLATE pg_catalog."default",
    email character VARYING
    (50) COLLATE pg_catalog."default",
    reg_date date,
    card_number character VARYING
    (15) COLLATE pg_catalog."default",
    date_of_birth date,
    gender character
    (1) COLLATE pg_catalog."default",
    CONSTRAINT customer_pkey PRIMARY KEY
    (customer_id)
);

CREATE TABLE
IF NOT EXISTS PUBLIC.product
(
    product_id integer NOT NULL,
    product_name character VARYING
(100) COLLATE pg_catalog."default",
    description character VARYING
(250) COLLATE pg_catalog."default",
    product_price DOUBLE precision,
    product_type_id integer,
    CONSTRAINT product_pkey PRIMARY KEY
(product_id)
);

CREATE TABLE
IF NOT EXISTS PUBLIC.product_type
(
    product_type_id integer NOT NULL,
    product_type character VARYING
(50) COLLATE pg_catalog."default",
    product_category character VARYING
(50) COLLATE pg_catalog."default",
    CONSTRAINT product_type_pkey PRIMARY KEY
(product_type_id)
);

CREATE TABLE
IF NOT EXISTS PUBLIC.sales_detail
(
    sales_detail_id integer NOT NULL,
    transaction_id integer,
    product_id integer,
    quantity integer,
    price DOUBLE precision,
    CONSTRAINT sales_detail_pkey PRIMARY KEY
(sales_detail_id)
);

CREATE TABLE
IF NOT EXISTS PUBLIC.sales_outlet
(
    sales_outlet_id integer NOT NULL,
    sales_outlet_type character VARYING
(20) COLLATE pg_catalog."default",
    address character VARYING
(50) COLLATE pg_catalog."default",
    city character VARYING
(40) COLLATE pg_catalog."default",
    telephone character VARYING
(15) COLLATE pg_catalog."default",
    postal_code integer,
    manager integer,
    CONSTRAINT sales_outlet_pkey PRIMARY KEY
(sales_outlet_id)
);

CREATE TABLE
IF NOT EXISTS PUBLIC.sales_transaction
(
    transaction_id integer NOT NULL,
    transaction_date date,
    transaction_time time without time zone,
    sales_outlet_id integer,
    staff_id integer,
    customer_id integer,
    CONSTRAINT sales_transaction_pkey PRIMARY KEY
(transaction_id)
);

CREATE TABLE
IF NOT EXISTS PUBLIC.staff
(
    staff_id integer NOT NULL,
    first_name character VARYING
(50) COLLATE pg_catalog."default",
    last_name character VARYING
(50) COLLATE pg_catalog."default",
    "position" character VARYING
(50) COLLATE pg_catalog."default",
    start_date date,
    location character VARYING
(5) COLLATE pg_catalog."default",
    CONSTRAINT staff_pkey PRIMARY KEY
(staff_id)
);

ALTER TABLE
IF EXISTS PUBLIC.product
ADD FOREIGN KEY
(product_type_id)
    REFERENCES PUBLIC.product_type
(product_type_id) MATCH SIMPLE
    ON
UPDATE NO ACTION
    ON
DELETE NO ACTION
    NOT VALID;


ALTER TABLE
IF EXISTS PUBLIC.sales_detail
ADD FOREIGN KEY
(transaction_id)
    REFERENCES PUBLIC.sales_transaction
(transaction_id) MATCH SIMPLE
    ON
UPDATE NO ACTION
    ON
DELETE NO ACTION
    NOT VALID;


ALTER TABLE
IF EXISTS PUBLIC.sales_detail
ADD FOREIGN KEY
(product_id)
    REFERENCES PUBLIC.product
(product_id) MATCH SIMPLE
    ON
UPDATE NO ACTION
    ON
DELETE NO ACTION
    NOT VALID;


ALTER TABLE
IF EXISTS PUBLIC.sales_transaction
ADD CONSTRAINT sales_transaction_customer_id_fkey FOREIGN KEY
(customer_id)
    REFERENCES PUBLIC.customer
(customer_id) MATCH SIMPLE
    ON
UPDATE NO ACTION
    ON
DELETE NO ACTION
    NOT VALID;


ALTER TABLE
IF EXISTS PUBLIC.sales_transaction
ADD CONSTRAINT sales_transaction_sales_outlet_id_fkey FOREIGN KEY
(sales_outlet_id)
    REFERENCES PUBLIC.sales_outlet
(sales_outlet_id) MATCH SIMPLE
    ON
UPDATE NO ACTION
    ON
DELETE NO ACTION
    NOT VALID;


ALTER TABLE
IF EXISTS PUBLIC.sales_transaction
ADD CONSTRAINT sales_transaction_staff_id_fkey FOREIGN KEY
(staff_id)
    REFERENCES PUBLIC.staff
(staff_id) MATCH SIMPLE
    ON
UPDATE NO ACTION
    ON
DELETE NO ACTION
    NOT VALID;

END;